(require 'bufshow)
(require 'color-theme-github)

(set-face-attribute 'default nil :family "Source_Code_Pro" :height 150)

(bufshow-start
 [("intro.txt" "title")
  ("intro.txt" "program-analysis-overview")
  ("intro.txt" "binary-analysis-overview")
  ("intro.txt" "overview-of-a-zero-stage")
  ("intro.txt" "loading-binary-1")
  ("intro.txt" "loading-binary-1")
  ("intro.txt" "what-is-value-1")
  ("intro.txt" "what-is-value-2")
  ("intro.txt" "what-is-value-3")
  ("intro.txt" "what-is-value-4")
  ("intro.txt" "back-to-loader")
  ("intro.txt" "overview-of-a-zero-stage-0-done")
  ("intro.txt" "disassembling")
  ("intro.txt" "where-to-get-roots")
  ("intro.txt" "initial-cfg")
  ("intro.txt" "welcome-bil")
  ("intro.txt" "overview-of-a-zero-stage-1-done")
  ("intro.txt" "symbol-reconstruction")
  ("intro.txt" "overview-of-a-zero-stage-2-done")
  ("intro.txt" "emit-code")
  ("intro.txt" "overview-of-a-zero-stage-2-done")
  ("intro.txt" "binary-analysis-overview-2")
  ("intro.txt" "welcome-IR")
  ("intro.txt" "welcome-IR-2")
  ("intro.txt" "IR-identity")
  ("intro.txt" "IR-structure")
  ("intro.txt" "bir-blk")
  ("intro.txt" "bir-example")
  ])


(set-face-attribute 'default nil :family "Source_Code_Pro" :height 160)
