(require 'bufshow)
(require 'color-theme-github)

(set-face-attribute 'default nil :family "Source_Code_Pro" :height 250)

(bufshow-start
 [("intro.txt" "greetings")
  ("intro.txt" "bottomup-vs-topdown")
  ("intro.txt" "entry-point")
  ("project.mli" "from_file")
  ("project.mli" "from_image")
  ("project.mli" "from_mem")
  ("project.mli" "from_bigstring")
  ("project.mli" "from_string")
  ("project.mli" "accessors")
  ("project.mli" "updaters")
  ("project.mli" "data-storage")
  ("intro.txt"   "program")
  ("intro.txt"   "example-1")
  ("intro.txt"   "control-flow")
  ("classes.mli"   "classes")
  ("term.mli"   "general-functions")
  ("term.mli"   "accessors")
  ("term.mli"   "enumerators")
  ("term.mli"   "updaters")
  ("term.mli"   "mappers")
  ("term.mli"   "navigators")
  ("terms.mli" "program-term") 
  ("terms.mli" "program-builder")  
  ("terms.mli" "sub-term") 
  ("terms.mli" "sub-builder") 
  ("terms.mli" "arg-term") 
  ("terms.mli" "arg-term-intent") 
  ("terms.mli" "blk-term-general") 
  ("terms.mli" "blk-split") 
  ("terms.mli" "blk-helpers") 
  ("terms.mli" "blk-builder") 
  ("terms.mli" "phi-term-start") 
  ("terms.mli" "phi-term-interface") 
  ("terms.mli" "def-term") 
  ("terms.mli" "jmp-description") 
  ("terms.mli" "jmp-create") 
  ("terms.mli" "label") 
  ("terms.mli" "call-term") 
  ("terms.mli" "jmp-accessors")
  ("intro.txt" "lets-get-ready-to-rumble")
  ("deadcode.ml" "start")
  ("ssa/deadcode_demo.ml" "clean-0")
  ("ssa/deadcode_demo.ml" "clean-1")
  ("ssa/deadcode_demo.ml" "collect-vars-init")
  ("ssa/deadcode_demo.ml" "vars-of-exp") 
  ("ssa/deadcode_demo.ml" "collect-vars-phi")
  ("ssa/deadcode_demo.ml" "collect-vars-phi+def")
  ("ssa/deadcode_demo.ml" "vars-of-label")
  ("ssa/deadcode_demo.ml" "collect-vars-phi+def+jmp")
  ("ssa/deadcode_demo.ml" "handling-side-effects")
  ])


(set-face-attribute 'default nil :family "Source_Code_Pro" :height 160)
